/* Generated By:JavaCC: Do not edit this line. SLPParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SLPParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SEMIC = 10;
  /** RegularExpression Id. */
  int ASSIGN = 11;
  /** RegularExpression Id. */
  int PRINT = 12;
  /** RegularExpression Id. */
  int LBR = 13;
  /** RegularExpression Id. */
  int RBR = 14;
  /** RegularExpression Id. */
  int COMMA = 15;
  /** RegularExpression Id. */
  int PLUS_SIGN = 16;
  /** RegularExpression Id. */
  int MINUS_SIGN = 17;
  /** RegularExpression Id. */
  int MULT_SIGN = 18;
  /** RegularExpression Id. */
  int DIV_SIGN = 19;
  /** RegularExpression Id. */
  int NUM = 20;
  /** RegularExpression Id. */
  int DIGIT = 21;
  /** RegularExpression Id. */
  int ID = 22;
  /** RegularExpression Id. */
  int LETTER = 23;
  /** RegularExpression Id. */
  int OTHER = 24;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"/*\"",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 9>",
    "\";\"",
    "\":=\"",
    "\"print\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "<NUM>",
    "<DIGIT>",
    "<ID>",
    "<LETTER>",
    "<OTHER>",
  };

}
