/* Generated By:JavaCC: Do not edit this line. ExprLangTreeConstants.java Version 5.0 */
public interface ExprLangTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTVOID = 1;
  public int JJTSTMS = 2;
  public int JJTDECL = 3;
  public int JJTADD_OP = 4;
  public int JJTBOOL_OP = 5;
  public int JJTNOT_OP = 6;
  public int JJTMULT_OP = 7;
  public int JJTEXP = 8;
  public int JJTNUMBER = 9;
  public int JJTIDENTIFIER = 10;


  public String[] jjtNodeName = {
    "program",
    "void",
    "Stms",
    "Decl",
    "Add_op",
    "Bool_op",
    "Not_op",
    "Mult_op",
    "Exp",
    "number",
    "identifier",
  };
}
/* JavaCC - OriginalChecksum=30922562493f3da69f9ecbbe6bb5bbcd (do not edit this line) */
