/* Generated By:JJTree&JavaCC: Do not edit this line. ExprLangConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExprLangConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LPAREN = 5;
  /** RegularExpression Id. */
  int RPAREN = 6;
  /** RegularExpression Id. */
  int ADD_OP = 7;
  /** RegularExpression Id. */
  int MULT_OP = 8;
  /** RegularExpression Id. */
  int NOT_OP = 9;
  /** RegularExpression Id. */
  int BOOL_OP = 10;
  /** RegularExpression Id. */
  int INT = 11;
  /** RegularExpression Id. */
  int BOOL = 12;
  /** RegularExpression Id. */
  int NUMBER = 13;
  /** RegularExpression Id. */
  int ID = 14;
  /** RegularExpression Id. */
  int SEMIC = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\" \"",
    "\"(\"",
    "\")\"",
    "<ADD_OP>",
    "<MULT_OP>",
    "\"~\"",
    "<BOOL_OP>",
    "\"int\"",
    "\"bool\"",
    "<NUMBER>",
    "<ID>",
    "\";\"",
  };

}
