/* Generated By:JJTree: Do not edit this line. ASTBIN_OPS.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBIN_OPS extends SimpleNode {
  public ASTBIN_OPS(int id) {
    super(id);
  }

  public ASTBIN_OPS(SLPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SLPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=44379b09e7f35eb9b9f5ab0836f66c9c (do not edit this line) */
