/* Generated By:JJTree: Do not edit this line. ASTbin_op.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTbin_op extends SimpleNode {
  public ASTbin_op(int id) {
    super(id);
  }

  public ASTbin_op(SLPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SLPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=fc3acec0c08d7a8b5e2f7b684e6c3a0b (do not edit this line) */
