/* Generated By:JJTree: Do not edit this line. ASTBLOCK.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBLOCK extends SimpleNode {
  public ASTBLOCK(int id) {
    super(id);
  }

  public ASTBLOCK(SLPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SLPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=83edfd8506a9dfa28b1c6b1e650ad2ec (do not edit this line) */
