/* Generated By:JJTree: Do not edit this line. ASTcomp_ops.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTcomp_ops extends SimpleNode {
  public ASTcomp_ops(int id) {
    super(id);
  }

  public ASTcomp_ops(SLPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SLPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d008186022f542f0be1f23473fb6812b (do not edit this line) */
