/* Generated By:JJTree: Do not edit this line. ASTCOMP_OPS.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCOMP_OPS extends SimpleNode {
  public ASTCOMP_OPS(int id) {
    super(id);
  }

  public ASTCOMP_OPS(SLPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SLPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4ab6e47703cc079b1f1b9391aac7a409 (do not edit this line) */
