/* Generated By:JJTree: Do not edit this line. ASTconst_decl.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTconst_decl extends SimpleNode {
  public ASTconst_decl(int id) {
    super(id);
  }

  public ASTconst_decl(SLPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SLPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6b5a2a826798e7cb0ebc89ebc05680a9 (do not edit this line) */
