/* Generated By:JJTree: Do not edit this line. ASTdecl_list.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTdecl_list extends SimpleNode {
  public ASTdecl_list(int id) {
    super(id);
  }

  public ASTdecl_list(SLPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SLPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=aa219fe2a0eb318cc5c6c2a44b5bdcec (do not edit this line) */
