/* Generated By:JJTree: Do not edit this line. ASTFRAGMENT.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFRAGMENT extends SimpleNode {
  public ASTFRAGMENT(int id) {
    super(id);
  }

  public ASTFRAGMENT(SLPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SLPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0f0cf9972d6e14ebb9497c6f7c585d9d (do not edit this line) */
