/* Generated By:JJTree: Do not edit this line. ASTfunc_call.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTfunc_call extends SimpleNode {
  public ASTfunc_call(int id) {
    super(id);
  }

  public ASTfunc_call(SLPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SLPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=370b8bd769fb5159cb7d2ca413385f98 (do not edit this line) */
