/* Generated By:JJTree: Do not edit this line. ASTlog_ops.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTlog_ops extends SimpleNode {
  public ASTlog_ops(int id) {
    super(id);
  }

  public ASTlog_ops(SLPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SLPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=bd10c2c4d207732686bece4acb02c250 (do not edit this line) */
