/* Generated By:JJTree: Do not edit this line. ASTLOG_OPS.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLOG_OPS extends SimpleNode {
  public ASTLOG_OPS(int id) {
    super(id);
  }

  public ASTLOG_OPS(SLPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SLPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0eba0aaf8794070a142947866f0c42b1 (do not edit this line) */
