/* Generated By:JJTree: Do not edit this line. ASTnemp_param_list.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTnemp_param_list extends SimpleNode {
  public ASTnemp_param_list(int id) {
    super(id);
  }

  public ASTnemp_param_list(SLPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SLPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e13434e013fdfae3c8d65c82930af3b4 (do not edit this line) */
