/* Generated By:JJTree: Do not edit this line. ASTPROGRAM.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTPROGRAM extends SimpleNode {
  public ASTPROGRAM(int id) {
    super(id);
  }

  public ASTPROGRAM(SLPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SLPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5921a077aff84854d9b8b27a948779e7 (do not edit this line) */
