/* Generated By:JJTree: Do not edit this line. ASTstatement_block.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTstatement_block extends SimpleNode {
  public ASTstatement_block(int id) {
    super(id);
  }

  public ASTstatement_block(SLPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SLPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0347aa8d079d44d3b8a33640d17b312a (do not edit this line) */
