/* Generated By:JJTree: Do not edit this line. ASTsimple_condition.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTsimple_condition extends SimpleNode {
  public ASTsimple_condition(int id) {
    super(id);
  }

  public ASTsimple_condition(SLPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SLPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=33c55476e1dfd24fc2a5228c37ce5972 (do not edit this line) */
