/* Generated By:JavaCC: Do not edit this line. SLPParserVisitor.java Version 5.0 */
public interface SLPParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTPROGRAM node, Object data);
  public Object visit(ASTcode node, Object data);
  public Object visit(ASTdecl_list node, Object data);
  public Object visit(ASTdecl node, Object data);
  public Object visit(ASTVAR node, Object data);
  public Object visit(ASTCONST node, Object data);
  public Object visit(ASTfunc node, Object data);
  public Object visit(ASTparam_list node, Object data);
  public Object visit(ASTnemp_param_list node, Object data);
  public Object visit(ASTparam node, Object data);
  public Object visit(ASTcondition node, Object data);
  public Object visit(ASTsimple_condition node, Object data);
  public Object visit(ASTcomp_ops node, Object data);
  public Object visit(ASTlog_ops node, Object data);
  public Object visit(ASTmain_statement node, Object data);
  public Object visit(ASTstatement_block node, Object data);
  public Object visit(ASTstatement node, Object data);
  public Object visit(ASTfunc_call node, Object data);
  public Object visit(ASTexpr node, Object data);
  public Object visit(ASTarg_list node, Object data);
  public Object visit(ASTnemp_arg_list node, Object data);
  public Object visit(ASTbin_op node, Object data);
  public Object visit(ASTfragment node, Object data);
  public Object visit(ASTid node, Object data);
  public Object visit(ASTreturn_statement node, Object data);
}
/* JavaCC - OriginalChecksum=c8675fbe67d3b920327f61a391bb6288 (do not edit this line) */
