/* Generated By:JavaCC: Do not edit this line. SLPParserTreeConstants.java Version 5.0 */
public interface SLPParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTCODE = 1;
  public int JJTVOID = 2;
  public int JJTDECL_LIST = 3;
  public int JJTDECL = 4;
  public int JJTVAR = 5;
  public int JJTCONST = 6;
  public int JJTFUNC = 7;
  public int JJTPARAM_LIST = 8;
  public int JJTNEMP_PARAM_LIST = 9;
  public int JJTPARAM = 10;
  public int JJTCONDITION = 11;
  public int JJTSIMPLE_CONDITION = 12;
  public int JJTCOMP_OPS = 13;
  public int JJTLOG_OPS = 14;
  public int JJTMAIN_STATEMENT = 15;
  public int JJTSTATEMENT_BLOCK = 16;
  public int JJTSTATEMENT = 17;
  public int JJTFUNC_CALL = 18;
  public int JJTEXPR = 19;
  public int JJTARG_LIST = 20;
  public int JJTNEMP_ARG_LIST = 21;
  public int JJTBIN_OP = 22;
  public int JJTFRAGMENT = 23;
  public int JJTID = 24;
  public int JJTRETURN_STATEMENT = 25;


  public String[] jjtNodeName = {
    "PROGRAM",
    "code",
    "void",
    "decl_list",
    "decl",
    "VAR",
    "CONST",
    "func",
    "param_list",
    "nemp_param_list",
    "param",
    "condition",
    "simple_condition",
    "comp_ops",
    "log_ops",
    "main_statement",
    "statement_block",
    "statement",
    "func_call",
    "expr",
    "arg_list",
    "nemp_arg_list",
    "bin_op",
    "fragment",
    "id",
    "return_statement",
  };
}
/* JavaCC - OriginalChecksum=9797a361974fbc59119a83091c3a819f (do not edit this line) */
