/* Generated By:JavaCC: Do not edit this line. SLPParserVisitor.java Version 5.0 */
public interface SLPParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTPROGRAM node, Object data);
  public Object visit(ASTVOID node, Object data);
  public Object visit(ASTVAR node, Object data);
}
/* JavaCC - OriginalChecksum=c9ae637e7b0fd40c22e86c6a930ccde8 (do not edit this line) */
