/* Generated By:JavaCC: Do not edit this line. SLPParserTreeConstants.java Version 5.0 */
public interface SLPParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTVOID = 1;
  public int JJTDECL = 2;
  public int JJTVAR = 3;
  public int JJTCONST = 4;
  public int JJTFUNCTION = 5;
  public int JJTSTATEMENT = 6;
  public int JJTCONDITION = 7;
  public int JJTCOMP_OPS = 8;
  public int JJTLOG_OPS = 9;
  public int JJTEXPR = 10;
  public int JJTARG = 11;
  public int JJTFRAGMENT = 12;
  public int JJTBIN_OPS = 13;
  public int JJTPARAM = 14;
  public int JJTRETURN = 15;
  public int JJTMAIN = 16;
  public int JJTID = 17;


  public String[] jjtNodeName = {
    "PROGRAM",
    "VOID",
    "decl",
    "VAR",
    "CONST",
    "FUNCTION",
    "STATEMENT",
    "CONDITION",
    "COMP_OPS",
    "LOG_OPS",
    "EXPR",
    "ARG",
    "FRAGMENT",
    "BIN_OPS",
    "PARAM",
    "RETURN",
    "MAIN",
    "ID",
  };
}
/* JavaCC - OriginalChecksum=7cf5c3a9b75098bf000a11a61a948d8f (do not edit this line) */
