/* Generated By:JavaCC: Do not edit this line. SLPParserTreeConstants.java Version 5.0 */
public interface SLPParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTVOID = 1;
  public int JJTVAR = 2;


  public String[] jjtNodeName = {
    "PROGRAM",
    "VOID",
    "VAR",
  };
}
/* JavaCC - OriginalChecksum=8b0ce43dd2517851f3a0a9a9f038fe26 (do not edit this line) */
